module.exports = function(API){
	const {Language, Errors: {ErrorCodes}} = API;
	Object.setPrototypeOf(this, Language.prototype);
	Language.call(this, "TL", {
		name: "TempLanguage",
		version: "0.1",
		author: "abc",
		description: "Template language"
	});
	this.api = {
		errors: {
			[ErrorCodes.Empty]: "",
			[ErrorCodes.ConnectionClosed]: "",
			[ErrorCodes.GameStateTimeout]: "",
			[ErrorCodes.RoomClosed]: "",
			[ErrorCodes.RoomFull]: "",
			[ErrorCodes.WrongPassword]: "",
			[ErrorCodes.BannedBefore]: "",
			[ErrorCodes.IncompatibleVersion]: "",
			[ErrorCodes.FailedHost]: "",
			[ErrorCodes.Unknown]: "",
			[ErrorCodes.Cancelled]: "",
			[ErrorCodes.FailedPeer]: "",
			[ErrorCodes.KickedNow]: "",
			[ErrorCodes.Failed]: "",
			[ErrorCodes.MasterConnectionError]: "",
			[ErrorCodes.StadiumParseError]: "",
			[ErrorCodes.StadiumParseSyntaxError]: "",
			[ErrorCodes.StadiumParseUnknownError]: "",
			[ErrorCodes.ObjectCastError]: "",
			[ErrorCodes.TeamColorsReadError]: "",
			[ErrorCodes.UTF8CharacterDecodeError]: "",
			[ErrorCodes.ReadTooMuchError]: "",
			[ErrorCodes.ReadWrongStringLengthError]: "",
			[ErrorCodes.EncodeUTF8CharNegativeError]: "",
			[ErrorCodes.EncodeUTF8CharTooLargeError]: "",
			[ErrorCodes.CalculateLengthOfUTF8CharNegativeError]: "",
			[ErrorCodes.CalculateLengthOfUTF8CharTooLargeError]: "",
			[ErrorCodes.BufferResizeParameterTooSmallError]: "",
			[ErrorCodes.BadColorError]: "",
			[ErrorCodes.BadTeamError]: "",
			[ErrorCodes.StadiumLimitsExceededError]: "",
			[ErrorCodes.MissingActionConfigError]: "",
			[ErrorCodes.UnregisteredActionError]: "",
			[ErrorCodes.MissingImplementationError]: "",
			[ErrorCodes.AnnouncementActionMessageTooLongError]: "",
			[ErrorCodes.ChatActionMessageTooLongError]: "",
			[ErrorCodes.KickBanReasonTooLongError]: "",
			[ErrorCodes.ChangeTeamColorsInvalidTeamIdError]: "",
			[ErrorCodes.MissingRecaptchaCallbackError]: "",
			[ErrorCodes.ReplayFileVersionMismatchError]: "",
			[ErrorCodes.ReplayFileReadError]: "",
			[ErrorCodes.JoinRoomNullIdAuthError]: "",
			[ErrorCodes.PlayerNameTooLongError]: "",
			[ErrorCodes.PlayerCountryTooLongError]: "",
			[ErrorCodes.PlayerAvatarTooLongError]: "",
			[ErrorCodes.PlayerJoinBlockedByMPDError]: "",
			[ErrorCodes.PlayerJoinBlockedByORError]: "",
			[ErrorCodes.PluginNotFoundError]: "",
			[ErrorCodes.PluginNameChangeNotAllowedError]: "",
			[ErrorCodes.LibraryNotFoundError]: "",
			[ErrorCodes.LibraryNameChangeNotAllowedError]: "",
			[ErrorCodes.AuthFromKeyInvalidIdFormatError]: "",
			[ErrorCodes.BadActorError]: "",
			[ErrorCodes.AuthBannedError]: "",
			[ErrorCodes.NoProxyIdentityProblem]: "",
			[ErrorCodes.NoProxyIdentitySolution]: ""
		}
	};
};